version: '3'

services:
  zabbix-web-server:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    links:
      - db
      - zabbix-server
      - mailserver
    ports:
      - "80:80"
      - "443:443"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_TZ: ${PHP_TZ}
    depends_on:
      - db
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-latest
    links:
      - zabbix-proxy
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-proxy
      ZBX_DEBUGLEVEL: ${ZBX_DEBUGLEVEL}
      ZBX_TIMEOUT: ${ZBX_TIMEOUT}
      ZBX_ENABLEREMOTECOMMANDS: ${ZBX_ENABLEREMOTECOMMANDS}
      ZBX_LOGREMOTECOMMANDS: ${ZBX_LOGREMOTECOMMANDS}
      ZBX_REFRESHACTIVECHECKS: ${ZBX_REFRESHACTIVECHECKS}
    depends_on:
      - zabbix-proxy

  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-latest
    links:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: zabbix-proxy
      ZBX_SERVER_HOST: zabbix-server
      ZBX_DEBUGLEVEL: ${ZBX_DEBUGLEVEL}
      ZBX_TIMEOUT: ${ZBX_TIMEOUT}
      ZBX_CONFIGFREQUENCY: ${ZBX_CONFIGFREQUENCY}
      ZBX_PROXYHEARTBEATFREQUENCY: ${ZBX_PROXYHEARTBEATFREQUENCY}
      ZBX_UNAVAILABLEDELAY: ${ZBX_UNAVAILABLEDELAY}
      ZBX_UNREACHABLEDELAY: ${ZBX_UNREACHABLEDELAY}
    depends_on:
      - zabbix-server

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-latest
    links:
      - db
      - mailserver
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ZBX_DEBUGLEVEL: ${ZBX_DEBUGLEVEL}
      ZBX_TIMEOUT: ${ZBX_TIMEOUT}
      ZBX_SENDERFREQUENCY: ${ZBX_SENDERFREQUENCY}
      ZBX_CACHEUPDATEFREQUENCY: ${ZBX_CACHEUPDATEFREQUENCY}
      ZBX_TRAPPERIMEOUT: ${ZBX_TRAPPERIMEOUT}
      ZBX_UNAVAILABLEDELAY: ${ZBX_UNAVAILABLEDELAY}
      ZBX_UNREACHABLEPERIOD: ${ZBX_UNREACHABLEPERIOD}
      ZBX_PROXYCONFIGFREQUENCY: ${ZBX_PROXYCONFIGFREQUENCY}
      ZBX_PROXYDATAFREQUENCY: ${ZBX_PROXYDATAFREQUENCY}
    depends_on:
      - db

  mailserver:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
